image: node:8.11.2
pipelines:
  branches:
    master:
      - step:
          script:
            - yarn install
            - yarn build
            - npm install -g firebase-tools
            - yarn deploy
